// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8OolMYjfn-Xk_EArr9tQfi0K9tAZkviI',
    appId: '1:377396282224:web:67ae0ebfc683152fce85b5',
    messagingSenderId: '377396282224',
    projectId: 'flutter-chat-app-3267e',
    authDomain: 'flutter-chat-app-3267e.firebaseapp.com',
    storageBucket: 'flutter-chat-app-3267e.firebasestorage.app',
    measurementId: 'G-XKWWMEQ83Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB04GaBFHvfxRTBPVrmDt5Wslqe9zAuXgM',
    appId: '1:377396282224:android:5cc15b20638d0340ce85b5',
    messagingSenderId: '377396282224',
    projectId: 'flutter-chat-app-3267e',
    storageBucket: 'flutter-chat-app-3267e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz4sduS3BdksHStS6cMXD9KP5FyeNXsew',
    appId: '1:377396282224:ios:e9f70a020309ee92ce85b5',
    messagingSenderId: '377396282224',
    projectId: 'flutter-chat-app-3267e',
    storageBucket: 'flutter-chat-app-3267e.firebasestorage.app',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz4sduS3BdksHStS6cMXD9KP5FyeNXsew',
    appId: '1:377396282224:ios:e9f70a020309ee92ce85b5',
    messagingSenderId: '377396282224',
    projectId: 'flutter-chat-app-3267e',
    storageBucket: 'flutter-chat-app-3267e.firebasestorage.app',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8OolMYjfn-Xk_EArr9tQfi0K9tAZkviI',
    appId: '1:377396282224:web:f5d03df5a2c3f6d7ce85b5',
    messagingSenderId: '377396282224',
    projectId: 'flutter-chat-app-3267e',
    authDomain: 'flutter-chat-app-3267e.firebaseapp.com',
    storageBucket: 'flutter-chat-app-3267e.firebasestorage.app',
    measurementId: 'G-0PN5MHRN0B',
  );
}
